#!/bin/bash

git pull
git add .
git commit -m "Update config on $(date)"
git push || true

set eux

PLATFORMS="linux/amd64,linux/arm64"

docker buildx build --platform $PLATFORMS -t yashanand1910/dev --load .

DOCKERFILE_DIR=$PWD
(
    cd "$HOME" || exit # since we are accessing some files from $HOME during build
    docker buildx build \
        --platform $PLATFORMS \
        --build-arg GITHUB_KEY="$GITHUB_KEY" \
        --build-arg DOCKERHUB_KEY="$DOCKERHUB_KEY" \
        -t yashanand1910/dev-private -f "$DOCKERFILE_DIR"/private.Dockerfile --load .
)

docker push yashanand1910/dev:latest
docker push yashanand1910/dev-private:latest

# docker system prune -f --volumes
# docker buildx prune -f
