ipc = on
preload = $HOME/wallpapers/clouds.png
splash = false

wallpaper {
    monitor = eDP-1
    path = $HOME/wallpapers/clouds.png
}
wallpaper {
    monitor = DP-2
    path = $HOME/wallpapers/clouds.png
}
wallpaper {
    monitor = HDMI-A-1
    path = $HOME/wallpapers/clouds.png
}
